### ISSUE TITLE
Verify cache settings on community server

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/webdashboard#123]
While working on https://github.com/mozilla-l10n/langchecker/pull/405 I noticed that the dashboard was incredibly slow (10-15 seconds to load), even when reloading after a few seconds. 

The only explanation I can think of is that we're not caching langchecker's results.

**Comment by pascalchevrel** [comment]
I flushed the cache, visited a page and I see cache files being created. I checked on langchecker side and the cache folder wasn't writable, this is fixed, that said personnally I didn't get any slowdown, I had generation times below 200ms.

**Comment by flodolo** [comment]
Thanks for checking.

Slowdowns wouldn't be as visible right now, see https://github.com/mozilla-l10n/langchecker/pull/405
The page took over 11 seconds to generate when I filed this PR.
